name: portainer-auto-recreate
description: hehe
author: Your name or organization here

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

# Define your inputs here.
inputs:
  portainer-host:
    description: The host URL for Portainer
    required: true
  username:
    description: The username for Portainer
    required: true
  password:
    description: The password for Portainer
    required: true
  containerName:
    description: The name of the container to recreate
    required: true

# Define your outputs here.
outputs:
  time:
    description: Your output description here

runs:
  using: node20
  main: dist/index.js
